### ISSUE TITLE
Using promises

### ISSUE THREAD

**Issue by mthenw** [serverless/stdlib-nodejs#11]
Right now the plan is to follow callback pattern. We might want to provide a way to return promise from each method or even make them promise-based only.

cc @nikgraf @eahefnawy @pmuens

**Comment by nikgraf** [comment]
In general I prefer Promises, especially since async/await syntax is really nice to work with and it's coming to JS.

The sad part about Promises nowadays is that they are somewhat broken. AWS solved it by allowing people to use their own promise dependency: `AWS.config.setPromisesDependency(require('bluebird'));`

https://aws.amazon.com/blogs/developer/support-for-promises-in-the-sdk/

**Comment by pmuens** [comment]
Yep. Also a big +1 for Promise usage (haven't used callbacks in a while (except for Lambda functions of course)).

Is it a big pain to maintain both from a code perspective? Otherwise I'd always vote for Promises.

Just curious: @nikgraf what exactly do you mean by "broken"? Do you mean the specification / implementation?

**Comment by mthenw** [comment]
> In general I prefer Promises, especially since async/await syntax is really nice to work with and it's coming to JS.

That's pretty significant argument.

I'm +1 for making stdlib promise based.
